---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://github.com/edx/configuration/wiki
# code style: https://github.com/edx/configuration/wiki/Ansible-Coding-Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
#
#
# Tasks for role hadoop_tasktracker
# 
# Overview:
# 
#
# Dependencies:
#
# 
# Example play:
#
#

- name: install system packages
  apt:
    pkg={{','.join(hadoop_tasktracker_debian_pkgs)}}
    state=present update_cache=yes
